version: '3.4'

services:
  courseapi:
    image: ${DOCKER_REGISTRY-}courseapi
    build:
      context: .
      dockerfile: CourseAPI/Dockerfile
    depends_on:
        - sqldata

  studentsapi:
    image: ${DOCKER_REGISTRY-}studentsapi
    build:
      context: .
      dockerfile: StudentsAPI/Dockerfile
    depends_on:
        - sqldata
  
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
       context: .
       dockerfile: ApiGateway/Dockerfile
    depends_on:
        - sqldata
        - courseapi
        - studentsapi

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
        - sqldata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  sqldata:
     image: mcr.microsoft.com/mssql/server:2019-latest 




 

