version: '3.4'

services:
  courseapi:
    image: ${DOCKER_REGISTRY-}courseapi
    build:
      context: .
      dockerfile: CourseAPI/Dockerfile
    depends_on:
        - sqldata

  studentsapi:
    image: ${DOCKER_REGISTRY-}studentsapi
    build:
      context: .
      dockerfile: StudentsAPI/Dockerfile
    depends_on:
        - sqldata
  
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
       context: .
       dockerfile: ApiGateway/Dockerfile
    depends_on:
        - sqldata
        - courseapi
        - studentsapi

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
        - sqldata

  sqldata:
     image: mcr.microsoft.com/mssql/server:2019-latest 




 

